name: Run the Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build-deb:
    strategy:
      matrix:
        codename:
          - bookworm
        platform:
          - amd64
          - arm64
          - arm/v7
          - ppc64le
          - 386

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

#    - name: Copy debian directory
#      run: cp -a packaging/debian .

    - name: Import PGP key
      run: |
        echo -n "${{ secrets.PGP_SIGNING_KEY_PRIVATE }}" | gpg --import
        echo -n "${{ vars.PGP_SIGNING_KEY_PUBLIC }}" | gpg --import

    - uses: andy5995/gh-action-build-deb@v1
      with:
        args: |
          --compression=xz
        codename: ${{ matrix.codename }}
        platform: ${{ matrix.platform }}

    - name: Create sha256sum
      run: |
        DEB_FILENAME=$(basename `find output/aprs-weather-submit_*deb`)
        echo "DEB_FILENAME=$DEB_FILENAME" >> $GITHUB_ENV
        cd output
        sha256sum "$DEB_FILENAME" > "../$DEB_FILENAME.sha256sum"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.DEB_FILENAME }}
        path: |
          output/*.deb
          *deb.sha256sum
        if-no-files-found: error

  publish-to-ppa:
    runs-on: ubuntu-latest
    steps:
    - name: Publish to PPA
      uses: yuezk/publish-ppa-package@v2
      with:
        repository: "rhymeswithmogul/aprs-weather-submit"
        gpg_private_key: ${{ secrets.PGP_SIGNING_KEY_PRIVATE }}
        gpg_passphrase: "foo"
        tarball: rhymeswithmogul/aprs-weather-submit-*/.build/tarball/*.tar.gz
        deb_email: "colin@colincogle.name"
        deb_fullname: "Colin Cogle"
#        keep_changelog: "yes"
